name: e-wallet
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:14.6-alpine
    restart: always
    environment:
      POSTGRES_DB: e_wallet
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwd
    ports:
      - '5432:5432'
    volumes:
      - ewallet_postgres_data:/var/lib/postgresql/data
    networks:
      - ewallet_network

  backend:
    container_name: backend
    image: abdo001/e-wallet:back
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/e_wallet
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: passwd
      JWT_SECRET: appSecretKey
    ports:
      - '8080:8080'
    depends_on:
      - postgres-db
    networks:
      - ewallet_network
  
  frontend:
    container_name: frontend
    image: abdo001/e-wallet:front
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - ewallet_network

  nginx:
    container_name: nginx
    image: nginx:1.21.5-alpine
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - frontend
    networks:
      - ewallet_network
      
volumes:
  ewallet_postgres_data:
    driver: local

networks:
  ewallet_network:
    driver: bridge
