- name: Deploy Full Stack App
  hosts: web_server
  become: yes

  tasks: 
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Install CertBot
      ansible.builtin.shell: sudo apt-get install certbot python3-certbot-nginx -y

    - name: remove existing containers
      ansible.builtin.shell: cd $HOME && docker-compose -f docker-compose.prod.yml down -v
      ignore_errors: yes

    - name: Copy Docker Compose file
      ansible.builtin.copy:
        src: ../../docker-compose.prod.yml
        dest: $HOME/docker-compose.prod.yml
    
    - name: Copy Nginx Config file
      ansible.builtin.copy:
        src: ../../nginx.conf
        dest: $HOME/nginx.conf

    - name: run the containers
      ansible.builtin.shell: cd $HOME && docker-compose -f docker-compose.prod.yml up -d

    - name: check the container status
      ansible.builtin.shell: docker ps