name: Frontend CI-CD pipeline

on:
  pull_request:
    branches: [ "master" ]
    paths: 
      - "e-wallet/frontend/**"

jobs:      
  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up the private key
        run: echo "${{ secrets.PRIVATE_KEY }}" > $HOME/google_key && chmod 600 $HOME/google_key 
        
      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          cd infra/ansible
          ansible-playbook -i inventory.ini frontend-deploy.yml
