name: 'Terraform'

on:
  pull_request:
    branches: [ "master" ]
    paths: 
    - "infra/**"
    
permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: |
          cd infra/terraform
          terraform init

      - name: Plan Terraform Deployment
        run: |
          cd infra/terraform
          terraform plan -var="ssh_public_key=${{ secrets.PUBLIC_KEY }}" -var="gcp_svc_key=${{ secrets.GCP_SVC_KEY }}"

      - name: Apply Terraform Deployment
        run: |
          cd infra/terraform
          terraform apply -auto-approve -var="ssh_public_key=${{ secrets.PUBLIC_KEY }}" -var="gcp_svc_key=${{ secrets.GCP_SVC_KEY }}"