name: 'Infra'

on:
  pull_request:
    branches: [ "master" ]
    paths: 
      - "infra/**"

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Set GOOGLE_APPLICATION_CREDENTIALS environment variable
        run: |
          echo '${{ secrets.GCP_SVC_KEY }}' > $HOME/gcp_key.json
          chmod 666 $HOME/gcp_key.json  # Ensure proper permissions

      - name: Initialize Terraform
        run: terraform -chdir=infra/terraform init

      - name: Format Terraform files (Auto-fix)
        run: terraform -chdir=infra/terraform fmt

      - name: Validate Terraform configuration
        run: terraform -chdir=infra/terraform validate

      - name: Check Terraform formatting (After Auto-fix)
        run: terraform -chdir=infra/terraform fmt -check

      - name: Plan Terraform Deployment
        run: terraform -chdir=infra/terraform plan -var="ssh_public_key=${{ secrets.PUBLIC_KEY }}"

      - name: Apply Terraform Deployment
        run: terraform -chdir=infra/terraform apply -auto-approve -var="ssh_public_key=${{ secrets.PUBLIC_KEY }}"

      - name: Get Terraform Output (VM IP)
        run: terraform -chdir=infra/terraform output -raw vm_ip > ~/infra/ansible/inventory.ini

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Set up the private key
        run: echo "${{ secrets.PRIVATE_KEY }}" > $HOME/.ssh/my_google_key && chmod 600 $HOME/.ssh/my_google_key 

      - name: Run Ansible Playbook
        run: |
          cd ~/infra/ansible
          ansible-playbook -i inventory.ini docker_setup.yml

      - name: Cleanup Google Cloud credentials
        if: always()
        run: rm -f $HOME/gcp_key.json
